version: '3'
services:
  server1:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis-stack

  server2:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis-stack

  redis-stack:
    image: redis/redis-stack:latest  
    ports:
      - "6379:6379" 
      - "8001:8001"  
    environment:
      - REDIS_PORT=6379
